spring.application.name=dates-bot
telegram.token=8484059906:AAGgKEd9YmlsuI6b9_rv2eER1FcGwjVKMMk
telegram.admin=878244736
telegram.channel=878244736
telegram.horario.inicio=10:00
telegram.horario.fin=02:00
telegram.aprob=true

spring.datasource.url=jdbc:sqlite:file:users.db?_journal_mode=WAL&_busy_timeout=5000
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SQLite works best with a small connection pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2